const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{bg1: 0},
	{Title: 0},
	{Play: 0},
	{Madeby: 0},
	{Touch: 0},
	{bg2: 0},
	{txtpertanyaan: 0},
	{ID: 0},
	{j1: 0},
	{j2: 0},
	{j3: 0},
	{j4: 0},
	{datasoal: 0},
	{tj1: 0},
	{tj2: 0},
	{tj3: 0},
	{tj4: 0},
	{SELAMATANDAMENANG: 0},
	{txtprogres: 0},
	{txtbenar: 0},
	{txtsalah: 0},
	{txtpesan: 0},
	{Audio: 0},
	{txtcoba: 0},
	{NoSoal: 0},
	{Skor: 0},
	{JumlahSalah: 0}
];

self.InstanceType = {
	bg1: class extends self.ISpriteInstance {},
	Title: class extends self.ITextInstance {},
	Play: class extends self.ITextInstance {},
	Madeby: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	bg2: class extends self.ISpriteInstance {},
	txtpertanyaan: class extends self.ITextInstance {},
	j1: class extends self.ISpriteInstance {},
	j2: class extends self.ISpriteInstance {},
	j3: class extends self.ISpriteInstance {},
	j4: class extends self.ISpriteInstance {},
	datasoal: class extends self.IArrayInstance {},
	tj1: class extends self.ITextInstance {},
	tj2: class extends self.ITextInstance {},
	tj3: class extends self.ITextInstance {},
	tj4: class extends self.ITextInstance {},
	SELAMATANDAMENANG: class extends self.ITextInstance {},
	txtprogres: class extends self.ITextInstance {},
	txtbenar: class extends self.ITextInstance {},
	txtsalah: class extends self.ITextInstance {},
	txtpesan: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	txtcoba: class extends self.ITextInstance {}
}